select 
    upper(trim(first)) as first_name, 
    upper(trim(last)) as last_name,
    upper(official_full) as full_name,
    case when birthday = '' then Null else cast(birthday as date) end as birthday,
    upper(trim(gender)) as gender,
    case when bioguide = '' then Null else bioguide end as bioguide,
    thomas,
    lis,
    govtrack,
    opensecrets,
    votesmart,
    fec,
    cspan,
    wikipedia,
    house_history,
    ballotpedia,
    maplight,
    icpsr,
    wikidata,
    google_entity_id
from $landing_house_reps